### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by agnibrainhack** [ResearchCodesHub/QuantumGeneticAlgorithms#1]
IndexError                                Traceback (most recent call last)
<ipython-input-14-3c6dc9971df0> in <module>
    269 print ("""QUANTUM GENETIC ALGORITHM""")
    270 input("Press Enter to continue...")
--> 271 Q_GA()
    272 plot_Output()

<ipython-input-14-3c6dc9971df0> in Q_GA()
    261       print("============== GENERATION: ",generation+1," =========================== ")
    262       print()
--> 263       rotation()
    264       mutation(0.01,0.001)
    265       generation=generation+1

<ipython-input-14-3c6dc9971df0> in rotation()
    177     for i in range(1,popSize):
    178        for j in range(1,genomeLength):
--> 179            if fitness[i]<fitness[best_chrom[generation]]:
    180              # if chromosome[i,j]==0 and chromosome[best_chrom[generation],j]==0:
    181                if chromosome[i,j]==0 and chromosome[best_chrom[generation],j]==1:

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

​

**Comment by adityag6994** [comment]
@agnibrainhack were you able to solve this ?


@ResearchCodesHub Thank you for sharing such an amazing code. Could you please assist me with this error?
